### ISSUE TITLE
Add minification and obfuscation to the deployment process

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#51]

**Comment by michaeljcalkins** [comment]
moved the dev dependencies to dependendcies
obfuscated code works

**Comment by michaeljcalkins** [comment]
ticket sent to heroku it should be working though once they figure out what's gong on

**Comment by michaeljcalkins** [comment]
```
-----> Node.js app detected
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
       NODE_ENV=production
       NODE_MODULES_CACHE=true
-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version (latest stable) via semver.io...
       Downloading and installing node 5.11.1...
       Using default npm version: 3.8.6
-----> Restoring cache
       Loading 2 from cacheDirectories (default):
       - node_modules
       - bower_components (not cached - skipping)
-----> Building dependencies
       Installing node modules (package.json)
       
       > phantomjssmith@0.4.6 preinstall /tmp/build_c740543ec729d0338090c8dc5518eba5/michaeljcalkins-rangersteve-c4a84c5a02104e51994d490fae1d3447fdf7ed36/node_modules/.staging/phantomjssmith-3ca09dea
       > phantomjs --version
       
       sh: 1: phantomjs: not found
       
       > canvas@1.1.6 install /tmp/build_c740543ec729d0338090c8dc5518eba5/michaeljcalkins-rangersteve-c4a84c5a02104e51994d490fae1d3447fdf7ed36/node_modules/canvas
       > node-gyp rebuild
       
       make: Entering directory `/tmp/build_c740543ec729d0338090c8dc5518eba5/michaeljcalkins-rangersteve-c4a84c5a02104e51994d490fae1d3447fdf7ed36/node_modules/canvas/build'
       SOLINK_MODULE(target) Release/obj.target/canvas-postbuild.node
       COPY Release/canvas-postbuild.node
       CXX(target) Release/obj.target/canvas/src/Canvas.o
       In file included from ../src/Canvas.h:22:0,
       from ../src/Canvas.cc:7:
       ../node_modules/nan/nan.h: In function ‘v8::Local<v8::Signature> NanNew(v8::Handle<v8::FunctionTemplate>, int, v8::Handle<v8::FunctionTemplate>*)’:
       ../node_modules/nan/nan.h:342:78: error: no matching function for call to ‘v8::Signature::New(v8::Isolate*, v8::Handle<v8::FunctionTemplate>&, int&, v8::Handle<v8::FunctionTemplate>*&)’
       return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
       ^
       ../node_modules/nan/nan.h:342:78: note: candidate is:
       In file included from ../src/Canvas.h:11:0,
       from ../src/Canvas.cc:7:
       /app/.node-gyp/5.11.1/include/node/v8.h:4674:27: note: static v8::Local<v8::Signature> v8::Signature::New(v8::Isolate*, v8::Local<v8::FunctionTemplate>)
       static Local<Signature> New(
       ^
       /app/.node-gyp/5.11.1/include/node/v8.h:4674:27: note:   candidate expects 2 arguments, 4 provided
       In file included from ../src/Canvas.h:22:0,
       from ../src/Canvas.cc:7:
       ../node_modules/nan/nan.h: At global scope:
       ../node_modules/nan/nan.h:424:3: error: redefinition of ‘v8::Local<T> NanNew(P) [with T = v8::StringObject; P = v8::Local<v8::String>]’
       NanNew<v8::StringObject, v8::Handle<v8::String> >(
       ^
       ../node_modules/nan/nan.h:417:3: error: ‘v8::Local<T> NanNew(P) [with T = v8::StringObject; P = v8::Local<v8::String>]’ previously declared here
       NanNew<v8::StringObject, v8::Local<v8::String> >(
       ^
       ../node_modules/nan/nan.h:442:36: error: redefinition of ‘template<class T> v8::Local<v8::RegExp> NanNew(v8::Local<v8::String>, v8::RegExp::Flags)’
       NAN_INLINE v8::Local<v8::RegExp> NanNew(
       ^
       ../node_modules/nan/nan.h:436:36: error: ‘template<class T> v8::Local<v8::RegExp> NanNew(v8::Handle<v8::String>, v8::RegExp::Flags)’ previously declared here
       NAN_INLINE v8::Local<v8::RegExp> NanNew(
       ^
       ../node_modules/nan/nan.h:454:36: error: redefinition of ‘template<class T, class P> v8::Local<v8::RegExp> NanNew(v8::Local<v8::String>, v8::RegExp::Flags)’
       NAN_INLINE v8::Local<v8::RegExp> NanNew(
       ^
       ../node_modules/nan/nan.h:448:36: error: ‘template<class T, class P> v8::Local<v8::RegExp> NanNew(v8::Handle<v8::String>, v8::RegExp::Flags)’ previously declared here
       NAN_INLINE v8::Local<v8::RegExp> NanNew(
       ^
       ../node_modules/nan/nan.h:623:19: error: ‘NanNew’ declared as an ‘inline’ variable
       v8::String::ExternalAsciiStringResource *resource) {
       ^
       ../node_modules/nan/nan.h:623:19: warning: ‘always_inline’ attribute ignored [-Wattributes]
       ../node_modules/nan/nan.h:623:19: error: ‘v8::Local<v8::String> NanNew’ redeclared as different kind of symbol
       ../node_modules/nan/nan.h:617:36: error: previous declaration of ‘v8::Local<v8::String> NanNew(v8::String::ExternalStringResource*)’
       NAN_INLINE v8::Local<v8::String> NanNew(
       ^
       ../node_modules/nan/nan.h:623:7: error: ‘ExternalAsciiStringResource’ is not a member of ‘v8::String’
       v8::String::ExternalAsciiStringResource *resource) {
       ^
       ../node_modules/nan/nan.h:623:48: error: ‘resource’ was not declared in this scope
       v8::String::ExternalAsciiStringResource *resource) {
       ^
       ../node_modules/nan/nan.h:637:27: error: redefinition of ‘template<class T> v8::Local<T> _NanEscapeScopeHelper(v8::Local<T>)’
       NAN_INLINE v8::Local<T> _NanEscapeScopeHelper(v8::Local<T> val) {
       ^
       ../node_modules/nan/nan.h:632:27: error: ‘template<class T> v8::Local<T> _NanEscapeScopeHelper(v8::Handle<T>)’ previously declared here
       NAN_INLINE v8::Local<T> _NanEscapeScopeHelper(v8::Handle<T> val) {
       ^
       ../node_modules/nan/nan.h:889:13: error: ‘node::smalloc’ has not been declared
       , node::smalloc::FreeCallback callback
       ^
       ../node_modules/nan/nan.h:889:35: error: expected ‘,’ or ‘...’ before ‘callback’
       , node::smalloc::FreeCallback callback
       ^
       ../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
       ../node_modules/nan/nan.h:893:50: error: ‘callback’ was not declared in this scope
       v8::Isolate::GetCurrent(), data, length, callback, hint);
       ^
       ../node_modules/nan/nan.h:893:60: error: ‘hint’ was not declared in this scope
       v8::Isolate::GetCurrent(), data, length, callback, hint);
       ^
       ../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
       ../node_modules/nan/nan.h:900:67: error: call of overloaded ‘New(v8::Isolate*, const char*&, uint32_t&)’ is ambiguous
       return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
       ^
       ../node_modules/nan/nan.h:900:67: note: candidates are:
       In file included from ../node_modules/nan/nan.h:179:0,
       from ../src/Canvas.h:22,
       from ../src/Canvas.cc:7:
       /app/.node-gyp/5.11.1/include/node/node_buffer.h:34:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
       NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
       ^
       /app/.node-gyp/5.11.1/include/node/node_buffer.h:34:40: note:   no known conversion for argument 3 from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’
       /app/.node-gyp/5.11.1/include/node/node_buffer.h:46:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
       NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
       ^
       /app/.node-gyp/5.11.1/include/node/node_buffer.h:46:40: note:   no known conversion for argument 2 from ‘const char*’ to ‘char*’
       In file included from ../src/Canvas.h:22:0,
       from ../src/Canvas.cc:7:
       ../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
       ../node_modules/nan/nan.h:904:61: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
       return node::Buffer::New(v8::Isolate::GetCurrent(), size);
       ^
       ../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
       ../node_modules/nan/nan.h:911:12: error: ‘Use’ is not a member of ‘node::Buffer’
       return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
       ^
       ../node_modules/nan/nan.h: In function ‘bool _NanGetExternalParts(v8::Handle<v8::Value>, const char**, size_t*)’:
       ../node_modules/nan/nan.h:1993:12: error: ‘class v8::String’ has no member named ‘IsExternalAscii’
       if (str->IsExternalAscii()) {
       ^
       ../node_modules/nan/nan.h:1994:11: error: ‘ExternalAsciiStringResource’ in ‘class v8::String’ does not name a type
       const v8::String::ExternalAsciiStringResource* ext;
       ^
       ../node_modules/nan/nan.h:1995:5: error: ‘ext’ was not declared in this scope
       ext = str->GetExternalAsciiStringResource();
       ^
       ../node_modules/nan/nan.h:1995:16: error: ‘class v8::String’ has no member named ‘GetExternalAsciiStringResource’
       ext = str->GetExternalAsciiStringResource();
       ^
       ../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
       ../node_modules/nan/nan.h:901:3: warning: control reaches end of non-void function [-Wreturn-type]
       }
       ^
       make: *** [Release/obj.target/canvas/src/Canvas.o] Error 1
       make: Leaving directory `/tmp/build_c740543ec729d0338090c8dc5518eba5/michaeljcalkins-rangersteve-c4a84c5a02104e51994d490fae1d3447fdf7ed36/node_modules/canvas/build'
       gyp ERR! build error
       gyp ERR! stack Error: `make` failed with exit code: 2
       gyp ERR! stack     at ChildProcess.onExit (/tmp/build_c740543ec729d0338090c8dc5518eba5/michaeljcalkins-rangersteve-c4a84c5a02104e51994d490fae1d3447fdf7ed36/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
       gyp ERR! stack     at emitTwo (events.js:100:13)
       gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
       gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
       gyp ERR! System Linux 3.13.0-95-generic
       gyp ERR! command "/tmp/build_c740543ec729d0338090c8dc5518eba5/michaeljcalkins-rangersteve-c4a84c5a02104e51994d490fae1d3447fdf7ed36/.heroku/node/bin/node" "/tmp/build_c740543ec729d0338090c8dc5518eba5/michaeljcalkins-rangersteve-c4a84c5a02104e51994d490fae1d3447fdf7ed36/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
       gyp ERR! cwd /tmp/build_c740543ec729d0338090c8dc5518eba5/michaeljcalkins-rangersteve-c4a84c5a02104e51994d490fae1d3447fdf7ed36/node_modules/canvas
       gyp ERR! node -v v5.11.1
       gyp ERR! node-gyp -v v3.3.1
       gyp ERR! not ok
       
       > rangersteve@0.0.0 postinstall /tmp/build_c740543ec729d0338090c8dc5518eba5/michaeljcalkins-rangersteve-c4a84c5a02104e51994d490fae1d3447fdf7ed36
       > gulp build --production
       
       [04:51:18] Using gulpfile /tmp/build_c740543ec729d0338090c8dc5518eba5/michaeljcalkins-rangersteve-c4a84c5a02104e51994d490fae1d3447fdf7ed36/gulpfile.js
       [04:51:18] Starting 'buildcss'...
       [04:51:18] Starting 'buildjs'...
       [04:51:18] Finished 'buildjs' after 18 ms
       app.css: 15302
       app.css: 11494
       [04:51:19] Finished 'buildcss' after 970 ms
       [04:51:19] Starting 'build'...
       [04:51:19] Finished 'build' after 12 μs
       JS Compiled!
       rangersteve@0.0.0 /tmp/build_c740543ec729d0338090c8dc5518eba5/michaeljcalkins-rangersteve-c4a84c5a02104e51994d490fae1d3447fdf7ed36
       └── UNMET PEER DEPENDENCY react@0.14.8
       
       npm ERR! code 1
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - Node version not specified in package.json
       https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
```
